# Generated by Django 4.1.2 on 2022-10-21 03:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0003_alter_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
