# Generated by Django 4.1.2 on 2022-11-12 12:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud_ajax", "0005_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="photo",
            name="caption",
            field=models.CharField(max_length=100, verbose_name="caption"),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name="body"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="title"),
        ),
    ]
